name: CI
on:
  - push
  - pull_request
jobs:
  x86_64-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "true"
      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0
      - name: build
        run: zig build
  x86_64-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "true"
      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0
      - name: build
        run: zig build
  x86_64-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "true"
      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0
      - name: build
        run: zig build
        env:
          AGREE: true
